FROM centos:7
ARG cvmfsversion=2.8.1

#RUN yum install -y http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm \
# && yum install -y cvmfs cvmfs-config-default cvmfs-fuse3 sudo vim openssh-clients \

COPY ./containers/install-cvmfs.sh /install-cvmfs.sh
COPY ./RPMS /RPMS
RUN sh /install-cvmfs.sh ${cvmfsversion} && rm /install-cvmfs.sh

RUN yum install -y https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi-latest.noarch.rpm

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_HTTP_PROXY="DIRECT"' >> /etc/cvmfs/default.local

RUN rm -rf /RPMS

RUN mkdir -p /cvmfs/{cvmfs-config.eessi-hpc.org,pilot.eessi-hpc.org}

RUN useradd -ms /bin/bash eessi
