FROM centos:7 AS prepare-rpm
COPY ./containers/build-or-download-cvmfs-rpm.sh /build-or-download-cvmfs-rpm.sh
RUN sh /build-or-download-cvmfs-rpm.sh

FROM centos:7
ARG cvmfsversion=2.8.1

#RUN yum install -y http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm \
# && yum install -y cvmfs cvmfs-config-default cvmfs-fuse3 sudo vim openssh-clients \

COPY --from=prepare-rpm /root/rpmbuild/RPMS /root/rpmbuild/RPMS
COPY ./containers/install-cvmfs.sh /install-cvmfs.sh

RUN ls -lR /root/rpmbuild

RUN sh /install-cvmfs.sh ${cvmfsversion} && rm /install-cvmfs.sh

RUN yum install -y https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi-latest.noarch.rpm

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_HTTP_PROXY="DIRECT"' >> /etc/cvmfs/default.local

RUN rm -rf /tmp/*.rpm

RUN mkdir -p /cvmfs/{cvmfs-config.eessi-hpc.org,pilot.eessi-hpc.org}

RUN useradd -ms /bin/bash eessi
