name: Build packages

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - build_packages
  pull_request:
    branches:
      - master
      - build_packages

jobs:
  build-packages:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Prepare package source
      uses: roles-ansible/check-ansible-debian-stretch-action@master
      with:
        targets: "./build-packages.yml"
        hosts: "localhost"

    - name: Build RPM package
      uses: kentik/pkg@v1.0.0-rc6
      with:
        name: cvmfs-config-eessi
        version: 0.1
        arch: x86_64
        format: rpm
        package: package.yaml

    - name: Build DEB package
      uses: kentik/pkg@v1.0.0-rc6
      with:
        name: cvmfs-config-eessi
        version: 0.1
        arch: x86_64
        format: deb
        package: "{{ github_workspace }}/package.yaml"

    - name: upload deb package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Deb package
        path: ${{ github.workspace }}/build/*.deb

    - name: upload rpm package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: RPM package
        path: ${{ github.workspace }}/build/noarch/*.rpm
