name: Build client packages

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - build_packages
  pull_request:
    branches:
      - master
      - build_packages

jobs:
  build-packages:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Get the version number for the packages
      id: get_version
      run: env TAG_NAME=${{ github.event.release.tag_name }} echo ::set-output name=version::${TAG_NAME:-0.0}

    - name: Prepare package source
      uses: roles-ansible/check-ansible-debian-stretch-action@master
      with:
        targets: "./build-packages.yml"
        hosts: "localhost"

    - name: Build RPM package
      id: build-rpm
      uses: kentik/pkg@v1.0.0-rc6
      with:
        name: cvmfs-config-eessi
        version: ${{ steps.get_version.outputs.version }}
        arch: x86_64
        format: rpm
        package: package/client_packages_metadata.yaml

    - name: Build DEB package
      id: build-deb
      uses: kentik/pkg@v1.0.0-rc6
      with:
        name: cvmfs-config-eessi
        version: ${{ steps.get_version.outputs.version }}
        arch: x86_64
        format: deb
        package: package/client_packages_metadata.yaml

    - name: upload deb package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Deb package
        path: ${{ steps.build-deb.outputs.package }}

    - name: upload rpm package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: RPM package
        path: ${{ steps.build-rpm.outputs.package }}
