name: Publish EESSI client Docker image
on: [push]
#  release:
#    types: [published]
 
jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        platform: [amd64, arm64]
        #, ppc64le]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.platform }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert and store repository owner in lowercase
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/client-pilot:centos7-${{ matrix.platform }}
          file: containers/Dockerfile.EESSI-client-pilot-centos7
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          #outputs: type=registry
          #tag_with_ref: true

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  create_manifest:
    name: Create the Docker manifest
    needs: push_to_registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Run docker manifest
        run: |
          export REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          docker manifest create \
            ghcr.io/${{ env.REPOSITORY_OWNER }}/client-pilot:centos7 \
            --amend ghcr.io/${{ env.REPOSITORY_OWNER }}/client-pilot:centos7-amd64 \
            --amend ghcr.io/${{ env.REPOSITORY_OWNER }}/client-pilot:centos7-arm64 \
            --amend ghcr.io/${{ env.REPOSITORY_OWNER }}/client-pilot:centos7-ppc64le
