name: Publish EESSI client Docker image
on: [push]
#  release:
#    types: [published]
 
jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, aarch64, ppc64le]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set architecture name for tag
        id: arch-tag
        run: |
          declare -A arch2tag
          arch2tag=( ["amd64"]="x86_64" ["arm64"]="aarch64" ["ppc64le"]="ppc64le")
          echo "::set-output arch=${arch2tag[${{ matrix.arch }}]}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/bedroge/client-pilot:centos7-${{ steps.arch-tag.arch }}
          file: containers/Dockerfile.EESSI-client-pilot-centos7-${{ steps.arch-tag.arch }}
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: true
          #outputs: type=registry
          #tag_with_ref: true
