name: Publish EESSI client Docker image
on: [push]
#  release:
#    types: [published]
 
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          #username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
          #registry: docker.pkg.github.com
          #tags: bedroge/filesystem-layer/eessi-client-pilot:centos7
          tags: ghcr.io/bedroge/eessi-client-pilot:centos7
          file: containers/Dockerfile.EESSI-client-pilot-centos7
          platforms: linux/amd64,linux/arm64
          push: true
          #outputs: type=registry
          #tag_with_ref: true
